# Generated by Django 5.1.11 on 2025-09-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', '-level', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('tech', 'Technical'), ('prof', 'Professional')], default='tech', max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Smaller shows first'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(help_text='0–100'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
